num1 = int(input("Number : "))
num2 = int(input("Number : "))
print(num1, "+", num2, "=", num1 + num2)
print(num1, "-", num2, "=", num1 - num2)
print(num1, "*", num2, "=", num1 * num2)
print(num1, "/", num2, "=", int(num1 / num2))